#ifndef __INTERFACE_H_
#define __INTERFACE_H_


#include "stm32f1xx_hal.h"


/******电机IO口定义******/
#define LEFT_PIN_F GPIO_PIN_13 
#define LEFT_GPIO_F GPIOG
#define LEFT_PIN_SET_F HAL_GPIO_WritePin(LEFT_GPIO_F,LEFT_PIN_F,GPIO_PIN_SET )
#define LEFT_PIN_RESET_F HAL_GPIO_WritePin(LEFT_GPIO_F,LEFT_PIN_F,GPIO_PIN_RESET)

#define LEFT_PIN_B GPIO_PIN_11
#define LEFT_GPIO_B GPIOG
#define LEFT_PIN_SET_B HAL_GPIO_WritePin(LEFT_GPIO_B,LEFT_PIN_B,GPIO_PIN_SET )
#define LEFT_PIN_RESET_B HAL_GPIO_WritePin(LEFT_GPIO_B,LEFT_PIN_B,GPIO_PIN_RESET)

#define RIGHT_PIN_F GPIO_PIN_11 
#define RIGHT_GPIO_F GPIOC
#define RIGHT_PIN_SET_F HAL_GPIO_WritePin(RIGHT_GPIO_F,RIGHT_PIN_F,GPIO_PIN_SET)
#define RIGHT_PIN_RESET_F HAL_GPIO_WritePin(RIGHT_GPIO_F,RIGHT_PIN_F,GPIO_PIN_RESET)

#define RIGHT_PIN_B GPIO_PIN_0 
#define RIGHT_GPIO_B GPIOD
#define RIGHT_PIN_SET_B HAL_GPIO_WritePin(RIGHT_GPIO_B,RIGHT_PIN_B,GPIO_PIN_SET)
#define RIGHT_PIN_RESET_B HAL_GPIO_WritePin(RIGHT_GPIO_B,RIGHT_PIN_B,GPIO_PIN_RESET)

#define LEFT_UP LEFT_PIN_SET_F;LEFT_PIN_RESET_B
#define RIGHT_UP RIGHT_PIN_SET_F;RIGHT_PIN_RESET_B

#define LEFT_DOWN LEFT_PIN_RESET_F;LEFT_PIN_SET_B
#define RIGHT_DOWN RIGHT_PIN_RESET_F;RIGHT_PIN_SET_B

#define LEFT_STOP LEFT_PIN_RESET_F;LEFT_PIN_RESET_B
#define RIGHT_STOP RIGHT_PIN_RESET_F;RIGHT_PIN_RESET_B

/******Trig信号IO口定义********/
#define Trig_Pin GPIO_PIN_8
#define Trig_GPIO GPIOD
#define Trig_HIGH HAL_GPIO_WritePin(Trig_GPIO,Trig_Pin,GPIO_PIN_RESET)
#define Trig_LOW  HAL_GPIO_WritePin(Trig_GPIO,Trig_Pin,GPIO_PIN_SET)
#endif
